### ISSUE TITLE
大佬救一下

### ISSUE THREAD

**Issue by lucky020323** [mhynbnb/anquanweike#3]
1.出现这个问题是怎么回事  File "D:\python\Lib\site-packages\requests\models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0) 
2.url，url2，url3需不需要改成自己的网址

**Comment by mhynbnb** [comment]
1.你给出的报错不完整，请给出完整的，需具体到主文件的某一行
2.不需要

**Comment by lucky020323** [comment]
完整的报错信息如下，请大佬明示！！
F:\anquanweike-main>python get_all_course.py
Traceback (most recent call last):
  File "D:\python\Lib\site-packages\requests\models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\anquanweike-main\get_all_course.py", line 41, in <module>
    course_info_list=rsp1.json()['data']
                     ^^^^^^^^^^^
  File "D:\python\Lib\site-packages\requests\models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by mhynbnb** [comment]
README里的参数都改了吗，这种情况应该是没有改对，导致获取不到正确的响应，json解析就会出现问题

**Comment by lucky020323** [comment]
大佬好，我按照README的方法对参数都进行了修改，并且在代码中存在的两个User-Agent我也进行了修改，但仍是无法运行。顺便问一下Cookie，User-Agent这两个参数在任一文件中都一样，我是不是可以选择任意一个文件中的都可以呀？万分感谢大佬！

**Comment by mhynbnb** [comment]
是可以



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月11日(周五) 下午5:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [mhynbnb/anquanweike] 大佬救一下 (Issue #3)




 
大佬好，我按照README的方法对参数都进行了修改，并且在代码中存在的两个User-Agent我也进行了修改，但仍是无法运行。顺便问一下Cookie，User-Agent这两个参数在任一文件中都一样，我是不是可以选择任意一个文件中的都可以呀？万分感谢大佬！

**Comment by lucky020323** [comment]
> 是可以
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年10月11日(周五) 下午5:57 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [mhynbnb/anquanweike] 大佬救一下 (Issue #3) 大佬好，我按照README的方法对参数都进行了修改，并且在代码中存在的两个User-Agent我也进行了修改，但仍是无法运行。顺便问一下Cookie，User-Agent这两个参数在任一文件中都一样，我是不是可以选择任意一个文件中的都可以呀？万分感谢大佬！ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

哎可是我还是报同样的错误

**Comment by mhynbnb** [comment]
可能是参数没找对



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月11日(周五) 晚上6:12
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [mhynbnb/anquanweike] 大佬救一下 (Issue #3)




  
是可以
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年10月11日(周五) 下午5:57 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [mhynbnb/anquanweike] 大佬救一下 (Issue #3) 大佬好，我按照README的方法对参数都进行了修改，并且在代码中存在的两个User-Agent我也进行了修改，但仍是无法运行。顺便问一下Cookie，User-Agent这两个参数在任一文件中都一样，我是不是可以选择任意一个文件中的都可以呀？万分感谢大佬！ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
哎可是我还是报同样的错误
